title: "Your AstroNotes"
subtitle: "Year 1 Notes in Astrophysics and Cosmology"
description: "A digital garden compiled directly from my Obsidian vault."
baseurl: ""
url: "https://yourastronotes.github.io"
github_repo: "yourastronotes/yourastronotes.github.io"
publish_tag: "*"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .github/

relative_links:
  enabled: false
